sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - wrk/bin
before_script:
  - "[ ! -f wrk/bin/wrk ] && rm -rf wrk && git clone https://github.com/wg/wrk.git && make -C wrk && mkdir wrk/bin && mv wrk/wrk wrk/bin || true"
  - export PATH=$PATH:$PWD/wrk/bin/
branches:
  only:
    - next
script:
  - npm run build
  - npm run bench
  - npm test
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
